*H**********************************************************************
* FILENAME :        tableEnumerations_PRCDB100.h             DESIGN REF: 
*
* DESCRIPTION :
*       This include file contains an enumeration for each table in the schema.
*
*    THIS FILE IS AN AUTO-GENERATED INCLUDE FILE
*
* PUBLIC FUNCTIONS :
*       None
*      
* NOTES :
*   
*
*       Copyright (c) Timothy Peer, eNVy Systems, Inc. 2015 -2018.  All rights reserved.
* 
* AUTHOR :    Timothy Peer        START DATE :    10 Nov 2018
*
* CHANGES :
*
* REF NO  VERSION DATE    WHO     DETAIL
*
*H*/

#ifndef tableEnumerations__h_PRCDB100
#define tableEnumerations__h_PRCDB100
	enum Rctables
		{
/*! An enumeration of tables supported by this interface.*/
/*! Enumerations are generated from output generated via the RMU/Extract/item=table DCL command*/
			enumPC_IDESREC=1			/*!<PRCDB100:PC_IDESREC*/
			,enumPC_FRMINGSET=2			/*!<PRCDB100:PC_FRMINGSET*/
			,enumPC_IXREC=3			/*!<PRCDB100:PC_IXREC*/
			,enumPC_ENDREC=4			/*!<PRCDB100:PC_ENDREC*/
			,enumPC_MBOMINGSET=5			/*!<PRCDB100:PC_MBOMINGSET*/
			,enumPC_WKCMPISET=6			/*!<PRCDB100:PC_WKCMPISET*/
			,enumPC_TEXDREC=7			/*!<PRCDB100:PC_TEXDREC*/
			,enumPC_FCODESREC=8			/*!<PRCDB100:PC_FCODESREC*/
			,enumPC_PRTENDSET=9			/*!<PRCDB100:PC_PRTENDSET*/
			,enumPC_FCOHHSHSET=10			/*!<PRCDB100:PC_FCOHHSHSET*/
			,enumPC_MPIREC=11			/*!<PRCDB100:PC_MPIREC*/
			,enumPC_FRMPVHSHSET=12			/*!<PRCDB100:PC_FRMPVHSHSET*/
			,enumPC_WKCPISET=13			/*!<PRCDB100:PC_WKCPISET*/
			,enumPC_WOHWODSET=14			/*!<PRCDB100:PC_WOHWODSET*/
			,enumPC_USRFRMPVSET=15			/*!<PRCDB100:PC_USRFRMPVSET*/
			,enumPC_FCOHFCODESSET=16			/*!<PRCDB100:PC_FCOHFCODESSET*/
			,enumPC_PIPISAFSET=17			/*!<PRCDB100:PC_PIPISAFSET*/
			,enumPC_INGIDESSET=18			/*!<PRCDB100:PC_INGIDESSET*/
			,enumPC_ALTHADTSET=19			/*!<PRCDB100:PC_ALTHADTSET*/
			,enumPC_TRKNOHSHSET=20			/*!<PRCDB100:PC_TRKNOHSHSET*/
			,enumPC_APIHAPITSET=21			/*!<PRCDB100:PC_APIHAPITSET*/
			,enumPC_PRTWODSET=22			/*!<PRCDB100:PC_PRTWODSET*/
			,enumPC_CHGHHSHSET=23			/*!<PRCDB100:PC_CHGHHSHSET*/
			,enumPC_APIHHSHSET=24			/*!<PRCDB100:PC_APIHHSHSET*/
			,enumPC_USRREC=25			/*!<PRCDB100:PC_USRREC*/
			,enumPC_MPISAFREC=26			/*!<PRCDB100:PC_MPISAFREC*/
			,enumPC_FRMFCODSET=27			/*!<PRCDB100:PC_FRMFCODSET*/
			,enumPC_APITREC=28			/*!<PRCDB100:PC_APITREC*/
			,enumPC_PRTMINGSET=29			/*!<PRCDB100:PC_PRTMINGSET*/
			,enumPC_WODREC=30			/*!<PRCDB100:PC_WODREC*/
			,enumPC_TEXTHSHSET=31			/*!<PRCDB100:PC_TEXTHSHSET*/
			,enumPC_PRTFRMSET=32			/*!<PRCDB100:PC_PRTFRMSET*/
			,enumPC_MPITWUSET=33			/*!<PRCDB100:PC_MPITWUSET*/
			,enumPC_INGSTEPSET=34			/*!<PRCDB100:PC_INGSTEPSET*/
			,enumPC_MBOWOHSET=35			/*!<PRCDB100:PC_MBOWOHSET*/
			,enumPC_ADFREC=36			/*!<PRCDB100:PC_ADFREC*/
			,enumPC_TRKNOREC=37			/*!<PRCDB100:PC_TRKNOREC*/
			,enumPC_CHGHREC=38			/*!<PRCDB100:PC_CHGHREC*/
			,enumPC_ADTDESREC=39			/*!<PRCDB100:PC_ADTDESREC*/
			,enumPC_MENDMCSTSET=40			/*!<PRCDB100:PC_MENDMCSTSET*/
			,enumPC_WKCHSHSET=41			/*!<PRCDB100:PC_WKCHSHSET*/
			,enumPC_CATREC=42			/*!<PRCDB100:PC_CATREC*/
			,enumPC_FCODREC=43			/*!<PRCDB100:PC_FCODREC*/
			,enumPC_MINGREC=44			/*!<PRCDB100:PC_MINGREC*/
			,enumPC_FRMHDESSET=45			/*!<PRCDB100:PC_FRMHDESSET*/
			,enumPC_CATFRMPVSET=46			/*!<PRCDB100:PC_CATFRMPVSET*/
			,enumPC_CHGHCHGDSET=47			/*!<PRCDB100:PC_CHGHCHGDSET*/
			,enumPC_FRMENDSET=48			/*!<PRCDB100:PC_FRMENDSET*/
			,enumPC_WOHHSHSET=49			/*!<PRCDB100:PC_WOHHSHSET*/
			,enumPC_PISAFREC=50			/*!<PRCDB100:PC_PISAFREC*/
			,enumPC_FCOHFCODSET=51			/*!<PRCDB100:PC_FCOHFCODSET*/
			,enumPC_FRMREC=52			/*!<PRCDB100:PC_FRMREC*/
			,enumPC_WKCAPITSET=53			/*!<PRCDB100:PC_WKCAPITSET*/
			,enumPC_MBOREC=54			/*!<PRCDB100:PC_MBOREC*/
			,enumPC_MBOMENDSET=55			/*!<PRCDB100:PC_MBOMENDSET*/
			,enumPC_PRTFCODSET=56			/*!<PRCDB100:PC_PRTFCODSET*/
			,enumPC_TRKNOTREC=57			/*!<PRCDB100:PC_TRKNOTREC*/
			,enumPC_TRKTRKNOTSET=58			/*!<PRCDB100:PC_TRKTRKNOTSET*/
			,enumPC_ALTHREC=59			/*!<PRCDB100:PC_ALTHREC*/
			,enumPC_STEPREC=60			/*!<PRCDB100:PC_STEPREC*/
			,enumPC_MBOMBODESSET=61			/*!<PRCDB100:PC_MBOMBODESSET*/
			,enumPC_SUBPREC=62			/*!<PRCDB100:PC_SUBPREC*/
			,enumPC_FRMHSHSET=63			/*!<PRCDB100:PC_FRMHSHSET*/
			,enumPC_WKCREC=64			/*!<PRCDB100:PC_WKCREC*/
			,enumPC_TOOREC=65			/*!<PRCDB100:PC_TOOREC*/
			,enumPC_PIDESREC=66			/*!<PRCDB100:PC_PIDESREC*/
			,enumPC_SLFREC=67			/*!<PRCDB100:PC_SLFREC*/
			,enumPC_MINGMIDESSET=68			/*!<PRCDB100:PC_MINGMIDESSET*/
			,enumPC_USRHSHSET=69			/*!<PRCDB100:PC_USRHSHSET*/
			,enumPC_PRTSLFSET=70			/*!<PRCDB100:PC_PRTSLFSET*/
			,enumPC_MBOHSHSET=71			/*!<PRCDB100:PC_MBOHSHSET*/
			,enumPC_CHGDREC=72			/*!<PRCDB100:PC_CHGDREC*/
			,enumPC_INGSIFSET=73			/*!<PRCDB100:PC_INGSIFSET*/
			,enumPC_HDESREC=74			/*!<PRCDB100:PC_HDESREC*/
			,enumPC_APITAPIDESSET=75			/*!<PRCDB100:PC_APITAPIDESSET*/
			,enumPC_ALTHHSHSET=76			/*!<PRCDB100:PC_ALTHHSHSET*/
			,enumPC_CATHSHSET=77			/*!<PRCDB100:PC_CATHSHSET*/
			,enumPC_TWUREC=78			/*!<PRCDB100:PC_TWUREC*/
			,enumPC_FCOHREC=79			/*!<PRCDB100:PC_FCOHREC*/
			,enumPC_TEXTREC=80			/*!<PRCDB100:PC_TEXTREC*/
			,enumPC_APIHAPIFSET=81			/*!<PRCDB100:PC_APIHAPIFSET*/
			,enumPC_APISAFREC=82			/*!<PRCDB100:PC_APISAFREC*/
			,enumPC_SLTREC=83			/*!<PRCDB100:PC_SLTREC*/
			,enumPC_CATIXSET=84			/*!<PRCDB100:PC_CATIXSET*/
			,enumPC_TRKREC=85			/*!<PRCDB100:PC_TRKREC*/
			,enumPC_TEXTTEXDSET=86			/*!<PRCDB100:PC_TEXTTEXDSET*/
			,enumPC_PRTHSHSET=87			/*!<PRCDB100:PC_PRTHSHSET*/
			,enumPC_PRTMBOSET=88			/*!<PRCDB100:PC_PRTMBOSET*/
			,enumPC_ADTADTDESSET=89			/*!<PRCDB100:PC_ADTADTDESSET*/
			,enumPC_MCSTREC=90			/*!<PRCDB100:PC_MCSTREC*/
			,enumPC_TOOTWUSET=91			/*!<PRCDB100:PC_TOOTWUSET*/
			,enumPC_ADTREC=92			/*!<PRCDB100:PC_ADTREC*/
			,enumPC_APITAPISAFSET=93			/*!<PRCDB100:PC_APITAPISAFSET*/
			,enumPC_ALTHADFSET=94			/*!<PRCDB100:PC_ALTHADFSET*/
			,enumPC_MPIDESREC=95			/*!<PRCDB100:PC_MPIDESREC*/
			,enumPC_APIDESREC=96			/*!<PRCDB100:PC_APIDESREC*/
			,enumPC_MBOMPISET=97			/*!<PRCDB100:PC_MBOMPISET*/
			,enumPC_PRTMENDSET=98			/*!<PRCDB100:PC_PRTMENDSET*/
			,enumPC_APIHREC=99			/*!<PRCDB100:PC_APIHREC*/
			,enumPC_APIFREC=100			/*!<PRCDB100:PC_APIFREC*/
			,enumPC_PRTSLTSET=101			/*!<PRCDB100:PC_PRTSLTSET*/
			,enumPC_SIFREC=102			/*!<PRCDB100:PC_SIFREC*/
			,enumPC_MBODESREC=103			/*!<PRCDB100:PC_MBODESREC*/
			,enumPC_MPIMPISAFSET=104			/*!<PRCDB100:PC_MPIMPISAFSET*/
			,enumPC_WOHREC=105			/*!<PRCDB100:PC_WOHREC*/
			,enumPC_TRKNOTRKSET=106			/*!<PRCDB100:PC_TRKNOTRKSET*/
			,enumPC_APITTWUSET=107			/*!<PRCDB100:PC_APITTWUSET*/
			,enumPC_CATFRMSET=108			/*!<PRCDB100:PC_CATFRMSET*/
			,enumPC_PRTINGSET=109			/*!<PRCDB100:PC_PRTINGSET*/
			,enumPC_PITWUSET=110			/*!<PRCDB100:PC_PITWUSET*/
			,enumPC_PRTREC=111			/*!<PRCDB100:PC_PRTREC*/
			,enumPC_PIREC=112			/*!<PRCDB100:PC_PIREC*/
			,enumPC_MPIMPIDESSET=113			/*!<PRCDB100:PC_MPIMPIDESSET*/
			,enumPC_ADTASTPSET=114			/*!<PRCDB100:PC_ADTASTPSET*/
			,enumPC_FRMPISET=115			/*!<PRCDB100:PC_FRMPISET*/
			,enumPC_IXHSHSET=116			/*!<PRCDB100:PC_IXHSHSET*/
			,enumPC_FRMPVREC=117			/*!<PRCDB100:PC_FRMPVREC*/
			,enumPC_PISUBPSET=118			/*!<PRCDB100:PC_PISUBPSET*/
			,enumPC_MIDESREC=119			/*!<PRCDB100:PC_MIDESREC*/
			,enumPC_PIPIDESSET=120			/*!<PRCDB100:PC_PIPIDESSET*/
			,enumPC_ASTPREC=121			/*!<PRCDB100:PC_ASTPREC*/
			,enumPC_MENDREC=122			/*!<PRCDB100:PC_MENDREC*/
			,enumPC_TOOHSHSET=123			/*!<PRCDB100:PC_TOOHSHSET*/
			,enumPC_INGREC=124			/*!<PRCDB100:PC_INGREC*/
		};
#endif // tableEnumerations__h_PRCDB100
